---
- name: Deploy website
  hosts: all
  vars:
    site_title: Default Site
    site_subtitle: Example Web Site
    deployed_by: Ansible
    debug_tools: True
  tasks:
    - debug:
        msg: Installing with debug tools enabled.
      when: debug_tools

    - name: IIS Web Server started
      win_feature:
        name: Web-Server
        state: present

    - name: HTTP Tracing is installed
      win_feature:
        name: Web-Http-Tracing
        state: present
      when: debug_tools

    - name: Index page is deployed
      win_template:
        src: templates/index.html.j2
        dest: C:\Inetpub\wwwroot\index.html

    - name: Info page is deployed
      win_copy:
        src: files/info.html
        dest: C:\Inetpub\wwwroot\info.html

    - name: Custom page is added
      win_copy:
        content: "Hello!"
        dest: C:\Inetpub\wwwroot\example.html
