---
  - name: Firewall rule is enabled
    ANSIBLE_MODULE:
      name: HTTP
      localport: "{{ iis_site_port }}"
      action: allow
      direction: in
      protocol: tcp
      state: present
      enabled: yes