---
- name: Web server with custom hosts file deployed
  hosts: all
  tasks:
    - name: IIS Web Server started
      win_feature:
        name: Web-Server
        state: present

    # Additional tasks here
