---
- name: Deploy example is cleaned up
  hosts: all
  vars:
    iis_site_path: C:\sites\projects
    iis_site_port: 8080

  tasks:
    - name: Firewall rule is removed
      win_firewall_rule:
        name: HTTP
        state: absent

    - name: IIS site is absent
      win_iis_website:
        name: "{{ item }}"
        state: absent
        port: "{{ iis_site_port }}"
        ip: "*"
        hostname: "{{ inventory_hostname }}"
        application_pool: DefaultAppPool
        physical_path: "{{ iis_site_path }}"
        parameters: logfile.directory:C:\sites\logs
      loop:
        - DO417-projects
        - DO417-windows
        - DO417-variables

    - name: Site directories are absent
      win_file:
        path: "{{ item }}"
        state: absent
      loop:
        - C:\sites\logs
        - "{{ iis_site_path }}"
