---
- name:  Creating an additional AD controller
  hosts: CHANGE_ME
  vars:
    domainname: CHANGE_ME
    dnsname: CHANGE_ME
    domain_admin: CHANGE_ME
    safe_password: CHANGE_ME

  tasks:
    - name: CHANGE_ME
      ANSIBLE_MODULE:
        dns_domain_name: CHANGE_ME
        domain_admin_user: CHANGE_ME
        domain_admin_password: CHANGE_ME
        safe_mode_password: CHANGE_ME
        state: CHANGE_ME
      register: domain_state

    - name: Rebooting to join the domain
      win_reboot:
        msg: "Rebooting..."
        reboot_timeout: 30
      when: domain_state.reboot_required
      ignore_errors: True
