- src: CHANGE_ME #replace with the URL link to the role's location
  version: CHANGE_ME #replace with the exact version of the role that you want to use
  name: CHANGE_ME #replace with a name that you want to give this role
